apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:26.4.2
          args: ["start-dev"]
          ports:
            - containerPort: 8080
          env:
            - name: KC_HOSTNAME
              value: keycloak.local
            - name: KC_PROXY
              value: edge
            - name: KC_DB
              value: postgres
            - name: KC_DB_URL
              # Using the verbose service name 'keycloak-postgres'
              value: "jdbc:postgresql://keycloak-postgres:5432/$(KC_DB_NAME)"

            # Injecting ENV vars from the secret
            - name: KC_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: keycloak-env-secrets
                  key: KEYCLOAK_POSTGRES_DB
            - name: KC_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: keycloak-env-secrets
                  key: KEYCLOAK_POSTGRES_USER
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-env-secrets
                  key: KEYCLOAK_POSTGRES_PASSWORD
            - name: KEYCLOAK_ADMIN
              valueFrom:
                secretKeyRef:
                  name: keycloak-env-secrets
                  key: KEYCLOAK_ADMIN
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-env-secrets
                  key: KEYCLOAK_ADMIN_PASSWORD

          # Readiness probe to ensure DB is up before Traffic
          readinessProbe:
            httpGet:
              path: /realms/master
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
spec:
  selector:
    app: keycloak
  ports:
    - port: 8080
      targetPort: 8080